Repository tjdgh925/CoCoBob-Front, pull requests merged in 2021-11, with the labels that each got.

#1 개발 환경 설정
  cocobob/package.json
  cocobob/src/App.css
  cocobob/src/App.test.tsx
  cocobob/src/index.css
  cocobob/src/logo.svg
  cocobob/src/setupTests.ts
  cocobob/yarn.lock
Labels: settings

#3 [CHORE]: 컴포넌트 기본 구조 설계
  cocobob/package.json
  cocobob/src/App.tsx
  cocobob/src/api/cocobob.ts
  cocobob/src/components/auth/index.tsx
  cocobob/src/components/common/Responsive.tsx
  cocobob/src/components/post/index.tsx
  cocobob/src/components/profile/index.tsx
  cocobob/src/features/auth/slices.tsx
  cocobob/src/features/post/slices.tsx
  cocobob/src/features/profile/slices.tsx
  cocobob/src/hooks/index.tsx
  cocobob/src/index.tsx
  cocobob/src/pages/auth/LoginPage.tsx
  cocobob/src/pages/auth/RegisterPage.tsx
  cocobob/src/pages/auth/index.tsx
  cocobob/src/pages/post/PostListPage.tsx
  cocobob/src/pages/post/PostPage.tsx
  cocobob/src/pages/post/WritePage.tsx
  cocobob/src/pages/post/index.tsx
  cocobob/src/pages/profile/ProfilePage.tsx
  cocobob/src/pages/profile/index.tsx
  cocobob/src/router/index.tsx
  cocobob/src/sagas/index.tsx
  cocobob/src/types/types.tsx
Labels: settings

#5 [FEAT] Login Page UI 설계 및 구현
  cocobob/package.json
  cocobob/src/App.tsx
  cocobob/src/components/auth/Login/LoginButtons.tsx
  cocobob/src/components/auth/Login/LoginFooter.tsx
  cocobob/src/components/auth/Login/LoginForm.tsx
  cocobob/src/components/auth/LoginForm.tsx
  cocobob/src/components/auth/Register/RegisterButton.tsx
  cocobob/src/components/auth/Register/RegisterForm.tsx
  cocobob/src/components/auth/Register/RegisterHeader.tsx
  cocobob/src/components/auth/index.tsx
  cocobob/src/components/common/ErrorMessage.tsx
  cocobob/src/components/common/Header.tsx
  cocobob/src/features/auth/slices.tsx
  cocobob/src/features/index.ts
  cocobob/src/hooks/index.tsx
  cocobob/src/hooks/useTypedSelector.ts
  cocobob/src/index.tsx
  cocobob/src/pages/auth/LoginPage.tsx
  cocobob/src/pages/auth/RegisterPage.tsx
  cocobob/src/pages/auth/index.tsx
  cocobob/src/types/types.tsx
  cocobob/yarn.lock
  image/loginPage-1.png
Labels: feat

#8 [STYLE] 로그인, 회원가입 페이지 Styled-Component 적용하기
  cocobob/package.json
  cocobob/src/components/auth/Login/LoginButtons.tsx
  cocobob/src/components/auth/Login/LoginFooter.tsx
  cocobob/src/components/auth/Login/LoginForm.tsx
  cocobob/src/components/auth/LoginForm.tsx
  cocobob/src/components/auth/Register/RegisterButton.tsx
  cocobob/src/components/auth/Register/RegisterForm.tsx
  cocobob/src/components/auth/Register/RegisterHeader.tsx
  cocobob/src/components/common/AuthHeader.tsx
  cocobob/src/components/common/Header.tsx
  cocobob/src/pages/auth/LoginPage.tsx
  cocobob/src/pages/auth/RegisterPage.tsx
  cocobob/yarn.lock
Labels: style

#10 [FEAT] Profile Page UI 설계 및 구현
  .DS_Store
  cocobob/.env
  cocobob/public/img/profileimage.png
  cocobob/src/App.tsx
  cocobob/src/components/common/Responsive.tsx
  cocobob/src/components/profile/ProfileHis.tsx
  cocobob/src/components/profile/ProfileImage.tsx
  cocobob/src/components/profile/ProfileInfo.tsx
  cocobob/src/components/profile/ProfileTab.tsx
  cocobob/src/features/index.ts
  cocobob/src/features/profile/slices.tsx
  cocobob/src/pages/profile/ProfilePage.tsx
Labels: feat

#12 [FEAT] Header Navigation Bar 구현
  cocobob/.gitignore
  cocobob/src/App.tsx
  cocobob/src/components/auth/Login/LoginButtons.tsx
  cocobob/src/components/auth/Register/RegisterButton.tsx
  cocobob/src/components/common/Button.tsx
  cocobob/src/components/common/HeaderTab.tsx
  cocobob/src/components/common/Responsive.tsx
  cocobob/src/index.tsx
Labels: feat

#15 [FEAT] 단일 게시물 페이지 UI 설계 및 구현
  cocobob/package-lock.json
  cocobob/package.json
  cocobob/src/App.tsx
  cocobob/src/components/auth/Register/RegisterForm.tsx
  cocobob/src/components/common/ContentInfo.tsx
  cocobob/src/components/common/Tags.tsx
  cocobob/src/components/post/ContentBody.tsx
  cocobob/src/components/post/ContentSideView.tsx
  cocobob/src/components/post/PostViewer.tsx
  cocobob/src/components/post/index.tsx
  cocobob/src/components/profile/ProfileTab.tsx
  cocobob/src/features/auth/slices.tsx
  cocobob/src/features/index.ts
  cocobob/src/features/post/slices.tsx
  cocobob/src/image/map.png
  cocobob/src/pages/auth/RegisterPage.tsx
  cocobob/src/pages/post/PostPage.tsx
  cocobob/src/types/types.tsx
  cocobob/yarn.lock
Labels: feat

#16 [FEAT] Home 화면 UI 설계 및 구현
  cocobob/public/img/BOB.png
  cocobob/public/img/CatholicLogo.png
  cocobob/public/img/step2.png
  cocobob/public/img/step3.png
  cocobob/src/App.tsx
  cocobob/src/components/home/Home.tsx
  cocobob/src/pages/home/HomePage.tsx
Labels: feat

#17 [STYLE] Home 화면 css 수정
  cocobob/src/components/home/Home.tsx
Labels: style

#19 [FIX] 상단 Nav Bar 오류 수정
  cocobob/src/App.tsx
  cocobob/src/components/auth/Login/LoginButtons.tsx
  cocobob/src/components/common/Button.tsx
  cocobob/src/components/common/HeaderTab.tsx
  cocobob/src/components/home/Home.tsx
Labels: fix

#21 [FEAT] 게시글 목록 조회화면 UI 설계 및 구현
  cocobob/package-lock.json
  cocobob/package.json
  cocobob/src/App.tsx
  cocobob/src/components/post/PostList.tsx
  cocobob/src/features/index.ts
  cocobob/src/features/postList/slices.tsx
  cocobob/src/image/test2.jpeg
  cocobob/src/pages/post/PostListPage.tsx
  cocobob/src/types/types.tsx
  cocobob/yarn.lock
Labels: feat

#23 [FEAT] 게시글 작성 페이지 UI 설계 및 구현
  cocobob/src/components/write/Editor.tsx
  cocobob/src/components/write/TagBox.tsx
  cocobob/src/components/write/WriteActionButtons.tsx
  cocobob/src/features/post/slices.tsx
  cocobob/src/pages/post/WritePage.tsx
Labels: feat

#25 [STYLE] 전체 컴포넌트에 테마 적용
  cocobob/package.json
  cocobob/public/img/Connect.png
  cocobob/src/App.tsx
  cocobob/src/components/auth/Login/LoginButtons.tsx
  cocobob/src/components/auth/Login/LoginForm.tsx
  cocobob/src/components/auth/Register/RegisterButton.tsx
  cocobob/src/components/auth/Register/RegisterForm.tsx
  cocobob/src/components/common/AuthHeader.tsx
  cocobob/src/components/common/Button.tsx
  cocobob/src/components/common/HeaderTab.tsx
  cocobob/src/components/home/Home.tsx
  cocobob/src/components/post/PostList.tsx
  cocobob/src/lib/styles/palette.ts
  cocobob/yarn.lock
Labels: style
